### ISSUE TITLE
Add MQTT support

### ISSUE THREAD

**Issue by jeroenhendricksen** [RaimondB/Detecticam#2]
To help ease adoption of this very useful application into the home automation world, support for MQTT should be added. I'd like to suggest adding the possibility of having a "detection"-event publish onto MQTT.

Of course this is a first step, as this could later be extended to with features like [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/) and providing set-up controls via MQTT, but let's start with the most essential part.

What should be configurable:
- a switch to enable mqtt support
- server (mandatory; a DNS name or IP)
- port (optional, default is 1883)
- username (optional, no/anonymous authentication if left empty)
- password (optional)
- topic prefix (optional, default could be `detecticam`)
- optionally, other MQTT settings, like QOS, keepalive time in seconds, clientId (auto-generated if left empty) and whether to always use a clean session.

Whenever there is motion detected for a specific camera, it could publish a message like this:
`{ "detection": true, "other_metadata": {} }`
or just simply
`true` (or `false`, when it also notifies about the absence of detection)

to a topic like `detecticam/<cameraname>/detection`

**Comment by RaimondB** [comment]
Indeed I think this would be very useful. To make it a bit pluggable I would see this as a possible action to link to detection on a stream. But at first we could just have a single configuration for all streams.
Personnally I would only be interested in detections, not in non-detections. But this could be a configurable option as well.

Also, I am thinking that it might be useful to add the detection data or classes. Something like:

```
{ "dectection" : true,
  "detections" : [
       {
           "class" : "person", 
           "probability" : 0.8 
       },
       {
           "class" : "car",
           "probability" : 0.6
       }    
    ]
}
```
Although these messages could become large if a lot of objects are detected. Currently, I whitelist to only detect persons, but YoloV3 can detect 80 classes of objects. Of a single frame, I have available all detected objects, its probability, and the bounding boxes on the image. This might be a little much :-) . So what would be most useful here?

**Comment by RaimondB** [comment]
@jeroenhendricksen I have added basic mqtt support, it can be pulled from docker hub with the tag detect-i-cam:dev .
Can you try it out for your scenario?

**Comment by jeroenhendricksen** [comment]
> @jeroenhendricksen I have added basic mqtt support, it can be pulled from docker hub with the tag detect-i-cam:dev .
> Can you try it out for your scenario?

It seems to work.

This is my config:
```
{
  "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "video-streams": [{
        "id": "FRONTDOOR",
        "path": "rtsp://unifi-video:7447/token",
        "fps": 15,
        "callbackUrl": ""
    }],
    "mqtt-publisher": {
        "enabled": true,
        "server": "rabbitmq",
        "port": 1883,
        "topicPrefix": "detecticam",
        "clientId": "detecticam"
    }
}
```

An this is a detection event being published successfully via MQTT:
<img width="1001" alt="Screen Shot 2020-07-23 at 10 28 03" src="https://user-images.githubusercontent.com/32140294/88266664-da3dc800-cccf-11ea-8ba4-44914b789634.png">

And this is what it looks like from the docker logs:
```
detect-i-cam    | [08:34:27.892] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 08:34:27.
detect-i-cam    | [08:34:27.892] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       Person detected for frame acquired at 07/23/2020 08:34:27. Sending to result processors
detect-i-cam    | [08:34:27.892] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 08:34:27. 1 objects detected
detect-i-cam    | [08:34:27.892] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       Detected: person#1
detect-i-cam    | [08:34:27.917] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       Interesting Detection Saved: obj-20200723T083427.jpg
detect-i-cam    | [08:34:30.873] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       Classifiy-objects ms:618
detect-i-cam    | [08:34:30.873] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 08:34:30.
detect-i-cam    | [08:34:30.873] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       Person detected for frame acquired at 07/23/2020 08:34:30. Sending to result processors
detect-i-cam    | [08:34:30.873] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 08:34:30. 2 objects detected
detect-i-cam    | [08:34:30.874] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       Detected: person#2
detect-i-cam    | [08:34:30.894] info: DetectiCam.Core.ResultProcessor.AnnotatedImagePublisher[0]
detect-i-cam    |       Interesting Detection Saved: obj-20200723T083430.jpg
```

**Comment by jeroenhendricksen** [comment]
> Indeed I think this would be very useful. To make it a bit pluggable I would see this as a possible action to link to detection on a stream. But at first we could just have a single configuration for all streams.
> Personnally I would only be interested in detections, not in non-detections. But this could be a configurable option as well.
> 
> Also, I am thinking that it might be useful to add the detection data or classes. Something like:
> 
> ```
> { "dectection" : true,
>   "detections" : [
>        {
>            "class" : "person", 
>            "probability" : 0.8 
>        },
>        {
>            "class" : "car",
>            "probability" : 0.6
>        }    
>     ]
> }
> ```
> 
> Although these messages could become large if a lot of objects are detected. Currently, I whitelist to only detect persons, but YoloV3 can detect 80 classes of objects. Of a single frame, I have available all detected objects, its probability, and the bounding boxes on the image. This might be a little much :-) . So what would be most useful here?

I don't need all 80 detected classes (if any), but I'l probably be building in some kind of filtering to acknowledge there 
1) being motion 
2) which (known) person is part of that motion

Maybe it would be helpful if a threshold could be set, so that only classifications with a certainty of more than X will be part of the event.

I see from the logs that you can identify there being multiple persons in the image snapshot. (I've seen `Person #1` and `Person #2`) already. Does this mean that a person, recognized before, can be recognized later (from a different camera as well) as belonging to the initial detected `Person #1`, and thereby allowing for the actual persons behind the person object being detected?

**Comment by jeroenhendricksen** [comment]
Another question. What are the supported classes? I've seen from the Yolo framework that it supports cats and dogs too. If I could also detect a cat (and no person), I could activate some kind of (don't worry people) cat-friendly way of scaring it away from my premise (a water jet or high frequency sound comes to mind). 

So maybe an option to configure what classes are detected/passed on, and an option to just pass them all on, with a configured limit where only the ones with the highest probability are sent.

**Comment by RaimondB** [comment]
> Another question. What are the supported classes? I've seen from the Yolo framework that it supports cats and dogs too. If I could also detect a cat (and no person in the same frame ;))

If you look at this file you can see the datafiles I am using for yolo3. I have put it in a different image for easy reuse and caching.
You need to check the coco.names file.

https://github.com/RaimondB/yolov3-data/blob/master/Dockerfile

**Comment by RaimondB** [comment]
> I don't need all 80 detected classes (if any), but I'l probably be building in some kind of filtering to acknowledge there
> 
> 1. being motion
> 2. which (known) person is part of that motion
> 
> Maybe it would be helpful if a threshold could be set, so that only classifications with a probability of more than X will be part of the event? That would make me ignore the `detection" : true`, as I would be calculating the fact that it's "detection" to me according to my own rules (unless I could configure that in the detecticam application).
> 
> I see from the logs that you can identify multiple persons from the image snapshot. (I've seen `Person #1` and `Person #2` already). Does this mean that a person- recognized before - can be recognized later (from a different camera as well) as belonging to the initial detected `Person #1`, and thereby allowing for the actual persons behind the person object being detected?

Threshold indeed would be easy to add as a config, and as well the labels to white-list. I think a single confidence level would be enough, not specifying it per-class. Currently I have it set hardcoded to only whitelist "person", with a confidence > 0.5 . But indeed you could also filter on cats. Although I have seen that cats, because of their size (the detector runs at a frame size of 320x320) are often recognized as bird, dogs and other animals. 

As for the <label>#<number> , I can see where the confusion is coming from, but yolo is not able to track objects. The number simply means "number of" so person#2 has detected 2 persons. If you configure the capture output, you can check the frame snapshots at the /capture volume to see the bounding boxes. 

With some custom training of the network it could be possible to detect a person by name for known persons, but then you require quite some training images that are labelled correctly.
