### ISSUE TITLE
Configure on what type of object(s) to trigger detection / callback

### ISSUE THREAD

**Issue by SierraNL** [RaimondB/Detecticam#30]
First of all, great tool to make the use of AI easy in home automation.

I noticed that OpenCV / Yolo detects a lot more than just persons. It would be great if you could configure per camera / stream what types of objects it should trigger on. And even cooler, to pass the type of object detected as a variable into the callback url.

**Comment by RaimondB** [comment]
This indeed I also had on my list and is fairly easy to do (at least the whitelisting part). For the callback url we could use the same kind of templating that I have built-in for MQTT.

**Comment by RaimondB** [comment]
I have created a new version in the pullrequest. You can test it by specifying the "dev" tag for the image instead of "latest"

**Comment by RaimondB** [comment]
@jeroenhendricksen this version might also interest you, since it now has the option to provide object detection details via MQTT.

**Comment by jeroenhendricksen** [comment]
> @jeroenhendricksen this version might also interest you, since it now has the option to provide object detection details via MQTT.

I've tried it with this config:
```
"mqtt-publisher": {
  [..]
  "includeDetectedObjects": true,
  "topDetectedObjectsLimit" : 3
},
"detection": {
  "detectionThreshold": 0.2,
  "objectWhitelist": [ "person", "car" ]
}
```

and it seems to work:

```
detecticam/detect-i-cam/FRONTDOOR/state {"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.9686221,"BoundingBox":{"X":1,"Y":137,"Width":224,"Height":222}}]}
detecticam/detect-i-cam/FRONTDOOR/state {"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.23587245,"BoundingBox":{"X":290,"Y":220,"Width":241,"Height":144}}]}
```

Great addition!
