### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by jeroenhendricksen** [RaimondB/Detecticam#5]
Application version: latest dev image as of today (2020-07-23)
Configuration: 
I have multiple RTSP streams specified. No changes with regards to logging inside the `appsettings.json`

*Description of the problem* 
In the log I find this from the docker logs output for the container:
```
                             [13:20:24.004] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       Classifiy-objects ms:1313
detect-i-cam    | [13:20:24.004] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 13:20:16.
detect-i-cam    | [13:20:24.004] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 13:20:20.
detect-i-cam    | [13:20:24.004] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
detect-i-cam    |       New result received for frame acquired at 07/23/2020 13:20:22.
detect-i-cam    | [h264 @ 0x7f309812db00] error while decoding MB 54 32, bytestream -6
detect-i-cam    | [h264 @ 0x7f309812db00] error while decoding MB 99 10, bytestream -16
detect-i-cam    | [h264 @ 0x7f309812db00] error while decoding MB 6 33, bytestream -6
detect-i-cam    | [h264 @ 0x7f30980c6160] error while decoding MB 91 38, bytestream -16
detect-i-cam    | [h264 @ 0x7f30980c6160] error while decoding MB 37 63, bytestream -10
detect-i-cam    | [h264 @ 0x7f309810c7c0] error while decoding MB 1 24, bytestream -20
```

*Suggested solution*
I think it would help if the related RTSP stream ID (eg. `FRONTDOOR`) was also printed as part of this info/error message. Besides I do not entirely understand whether this "error while decoding" is an actual problem, as the message severity is set to `info`. This could be clarified maybe?

**Comment by RaimondB** [comment]
The error you are seeing is related to decoding the camera stream, and basically means the frame capture cannot keep up. If it starts lagging, these decoding error occur. They come directly from opencv logged to the console, so I cannot improve them.
I was planning on an improved way for the framecapture since I am now relying on async/await and Task.Delay which does not give guaranteed waiting times.

To remove the error, it is a possibility to use a stream with a smaller resolution. Since the detector is only using 320x320, anything bigger is basically only burning CPU and not adding to the quality ;-)

**Comment by jeroenhendricksen** [comment]
> The error you are seeing is related to decoding the camera stream, and basically means the frame capture cannot keep up. If it starts lagging, these decoding error occur. They come directly from opencv logged to the console, so I cannot improve them.
> I was planning on an improved way for the framecapture since I am now relying on async/await and Task.Delay which does not give guaranteed waiting times.
> 
> To remove the error, it is a possibility to use a stream with a smaller resolution. Since the detector is only using 320x320, anything bigger is basically only burning CPU and not adding to the quality ;-)

That I didn't know and would probably help reduce cpu load as well. I'll switch my RTSP streams to 640 x 360 pixels, see what it does with cpu load.
