### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by jeroenhendricksen** [RaimondB/Detecticam#6]
This is a graph showing the memory usage for the detect-i-cam dev version. As you can see it rises over time, without flattening out. It has (only) been running for 2,5h straight out, which is not long of course.

<img width="931" alt="Screen Shot 2020-07-23 at 17 37 44" src="https://user-images.githubusercontent.com/32140294/88306642-4689ed00-cd0b-11ea-9636-3a0d9c3b1b34.png">

So I'm not sure if it's a problem. Therefore I'll start running it for a longer period and monitor the memory usage.
I'm guessing you need more info, but I'm not sure what you need that would help. Do I need to create a heap dump maybe? Let me know.

**Comment by RaimondB** [comment]
I'll look into it. I am probable forgetting to Release/Dispose an image somewhere.
Seen it before in earlier builds.

Although I don't have the issue. And I am also running the dev tag. Can you recheck with pulling the latest dev images?

![image](https://user-images.githubusercontent.com/12556944/88328793-3e40aa80-cd29-11ea-9134-8edf3a1d3550.png)

**Comment by jeroenhendricksen** [comment]
<img width="622" alt="Screen Shot 2020-07-27 at 13 36 11" src="https://user-images.githubusercontent.com/32140294/88537637-34ab9100-d00e-11ea-9590-a570921b0d8f.png">

I think it's no longer an issue now. Memory usage is very stable. Test with 3 low resolutions RTSP streams and 2 FPS.
